---
title: "appropriate_abx_public"
author: "Julie Yarahuan"
date: '2022-09-08'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Define Variables

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. 

```{r,echo=FALSE, message=FALSE}
#Load Libraries
library(tidyr)
library(tibble)
library(dplyr)
library(readr)
library(lubridate)
library(stringr)
library(data.table)
library(tinytex)

```

```{r, echo=FALSE, message=FALSE}
##Input your variables here##

#File path variable: Input your file path here
abxfile="/Volumes/dmcommon/_DM.Private/CI Program Faculty/+Fellow Franchise/Yarahuan/Protected/Antibiotics with Transfer History.csv"
culturefile="/Volumes/dmcommon/_DM.Private/CI Program Faculty/+Fellow Franchise/Yarahuan/Protected/Positive Blood or Respiratory Cultures with organism.csv"

#Load Datasets
abxdata <- read_csv(abxfile)
culturedata<-read_csv(culturefile)

#########TRAINING/TESTING ONLY############
#import CSN list 2/3 split for training & filter data for those CSNs only
csnlisttrain<-read_csv("/Volumes/dmcommon/_DM.Private/CI Program Faculty/+Fellow Franchise/Yarahuan/Protected/CSNListTRAIN.csv")
abxdata<-abxdata %>%
  filter(`Contact Serial Number` %in% csnlisttrain$x)

#column names for antibiotics table, make sure your data is in the below order: 
#1=contact serial number (encounter ID), 2=MRN, 3=date of birth, 4= Admit DateTime, 5=Discharge Service Abbreviation, 6= Discharge Service description, 7=Service on a given date, 8= date of service, 9=ICD10 code, 10=ICD 10 description,
#11=Medication Order DateTime, 12=Medication, 13=allergy substance, 14=allergy type

#rename columns in abx data
abxdata<-abxdata %>%
  rename(CSN=1) %>%
  rename(MRN=2) %>%
  rename(DOB=3) %>%
  rename(AdmitDT=4) %>%
  rename(DischargeService=5) %>%
  rename(DischargeServiceDesc=6) %>%
  rename(BeddedService=7)%>%
  rename(BeddedDate=8)%>%
  rename(ICD=9) %>%
  rename(ICDdesc=10) %>%
  rename(MedDT=11) %>%
  rename(Med=12) %>%
  rename(Allergy=13) %>%
  rename(AllergyType=14)

#column names for culture table, make sure your data is in the following order
#1=MRN, 2=lab order, 3=Collection DT, 4= Organism, 5=suceptibility (eg. susceptble or resistant), 6= antibiotic susceptbility (antibiotic name), 7=susceptibility result DT

#rename columns in culture data
culturedata<-culturedata %>%
  rename(MRN=1) %>%
  rename(LabOrder=2)%>%
  rename(CollectionDT=3)%>%
  rename(Organism=4)%>%
  rename(Susceptibility=5)%>%
  rename(SusceptibilityAntibiotic=6)%>%
  rename(SusceptibilityDT=7)

```

```{r}
#Count unique starting CSNs
csnunique <- unique(abxdata$CSN)
length(csnunique)
```

```{r,echo=FALSE, message=FALSE}
#Join Datasets

#reformat MRN as numeric in culture dataset
culturedata$MRN <- as.numeric(culturedata$MRN)

#join abx with cultures
abxculturedata= abxdata %>% left_join(culturedata,by="MRN")
```

```{r,echo=FALSE, message=FALSE}
#Show table to ensure columns & data are loaded and joined correctly
head(abxculturedata)
```



```{r, echo=FALSE}
################################# Clean Dataset ########################################

#reformat date in culture dataset
abxculturedata$CollectionDT<-mdy_hms(abxculturedata$CollectionDT)
abxculturedata$SusceptibilityDT<-mdy_hms(abxculturedata$SusceptibilityDT)

#reformat dates for admit DT and DOB
abxculturedata$AdmitDT<-mdy_hms(abxculturedata$AdmitDT, truncated = 1)
abxculturedata$DOB<-mdy(abxculturedata$DOB)
abxculturedata$MedDT<-mdy_hms(abxculturedata$MedDT)

#Calculate age in years at time of admission
abxculturedata <- abxculturedata %>%
  mutate(age=year(AdmitDT)-year(DOB))

#calculate age in months at time of admission
abxculturedata<-abxculturedata %>%
  mutate(agemonths=interval(DOB,AdmitDT) %/% months(1))

#define inpatient vs ED encounters
abxculturedata<-abxculturedata %>%
  mutate(servicelocation= if_else(DischargeService=="EMR","Emergency","Inpatient",missing=NULL))

#make text columns lowercase
abxculturedata$ICDdesc=tolower(abxculturedata$ICDdesc)
abxculturedata$Med=tolower(abxculturedata$Med)
abxculturedata$Allergy=tolower(abxculturedata$Allergy)
abxculturedata$SusceptibilityAntibiotic=tolower(abxculturedata$SusceptibilityAntibiotic)
abxculturedata$Susceptibility=tolower(abxculturedata$Susceptibility)
```


```{r, echo=FALSE}
#Count unique starting CSNs
csnunique <- unique(abxculturedata$CSN)
length(csnunique)
```


```{r, echo=FALSE}
paste("Total starting encounters: ",length(csnunique))

```



## Define  guideline exclusions and guideline choices 
```{r, echo=FALSE}
#Select services of interest
servicesofinterest<-c('PMA','PMB','PMC','PMD','CCS','PUL','EMR','ADL') 

#services to exclude: this is to exclude patients who were admitted first to another service (like the ICU or a surgical service) and then transferred to PHM
prePHMservicetoexclude<-c("Intermediate Care Program","Medicine Critical Care","Medical Intensive Care")

#Ages to exclude (e.g. this guideline excludes children less than 3 months old)
minagemonths=3

#Co-morbid conditions to exclude (make all lowercase)
exclusiondiagnoses=c("cystic fibrosis","other specified congenital malformations of respiratory system","sickle-cell","hb-ss","sickle cell","leukemia","lymphoma",'neoplasm','transplant',"tuberculosis",
                     "tracheostomy","end stage renal","immunodeficiency",'immunodeficiencies','hypogammaglobulinemia','di george',
                     "rheumatoid arthritis","lupus","muscular dystrophy","spinal muscular atrophy","hypoplastic left heart syndrome",
                     "pulmonary hypertension","cardiomyopathy","heart failure")


#filter out some common infections based on ICD prefixes
#AO: exclude infectious colitis, "B0*":exclude many viral infections, "J95.851":exclude ventilator assc PNA, "M00*":septic arthritis,  "M01*": septic arthritis,"N39*": exclude UTI
exclusioninfections<-c("A0*","B0*","J95.851", "M00*","M01*","N39*")
exclusioninfections2=c("abscess","cellulitis", "osteomyelitis",
                     "mastoiditis","lymphangitis","sinusitis","streptococcal pharyngitis","impetigo","lymphadenitis",
                     "omphalitis","aspiration","arthritis due to other bacteria","myositis","sinusitis",'pyelonephritis')

#filter out certain antimicrobials
exclusionantimicrobials<- c('oseltamivir','bacitracin','nystatin','valacyclovir','hydroxychloroquine','erythromycin')

#identify list of pneumonia ICD codes of interest (these are the codes of pneumonia that you are INCLUDING in your table)
pnalist<-c('J13', 'J13', 'J14', 'J14', 'J15.0', 'J15.0', 'J15.1', 'J15.1', 'J15.20', 'J15.20', 'J15.211', 'J15.211', 'J15.212', 'J15.212', 'J15.29', 'J15.29', 'J15.3', 'J15.3', 'J15.4', 'J15.4', 'J15.5', 'J15.5', 'J15.6', 'J15.6', 'J15.7', 'J15.7', 'J15.8', 'J15.8', 'J15.9', 'J15.9', 'J16.0', 'J16.0', 'J16.8', 'J17', 'J18.0', 'J18.1', 'J18.8', 'J18.9', 'J85.1', 'J95.851', 'J95.851')

#define first line choices 
#####first line is ampicillin or amoxicillin
#####if PCN allergy then, ceftriaxone, clindamycin, cefdinir, levofloxacin
#####if cephalosporin allergy then, levofloxacin, clindamycin
#first line atypical coverage is azithromycin
######if azithromycin allergy then levofloxacin or doxycycline
firstline=c("amoxicillin","ampicillin")
PCNallergy=c("amoxicillin","ampicillin",'penicillin','augmentin','penicillins','amoxicillin-clavulanate') #list of meds that count as PCN allergy
ifPCNallergy=c("ceftriaxone","clindamycin","cefdinir",'levofloxacin')
cephalosporinallergy=c("cefdinir","cefotaxime","ceftriaxone","cephalexin","cephalosporins","cefuroxime","cefazolin","cefadroxil","cefotetan","cefoxitin","ceftazidime","cefpodoxime","cefixime","cefepime","ceftaroline") #list of meds that count as cephalosporin allergy
ifcephalosporinallergy=c("levofloxacin","clindamycin")
atypicalfirstline="azithromycin"
azithroallergy="azithromycin"
atypicalwithazithroallergy=c("levofloxacin","doxycycline")

#if over 4 then azithromycin is potentially appropriate
ageforazithro=4 

```




```{r, echo=FALSE}
################################# Define culture exclusions ########################################

#pcnresistance list
narrowpcnsusceptibilitylist<-c("ampicillin","oxacillin",'Penicillin (meningitis)','Penicillin (non-meningitis)')
broadpcnsuscetiblitylist<-c("ampicillin","oxacillin",'ampicillin/sulbactam','Penicillin (meningitis)','Penicillin (non-meningitis)')
```

# Output

## Summary of reasons for exlusion
```{r, echo=FALSE}
################################# Apply guideline exclusions ########################################
#eliminate patients less than your min exclusion age
abxculturedata <- abxculturedata %>%
  mutate(reasonforexclusions= if_else(
    agemonths>=minagemonths,"Included","Below min age"))


#select services of interest (discharge service=PHM)
abxculturedata <- abxculturedata %>%
  mutate(reasonforexclusions= if_else(
    (DischargeService %in% servicesofinterest) &reasonforexclusions=="Included","Included",
    if_else(reasonforexclusions!="Included",reasonforexclusions,"Excluded service")))

#filter out patients admitted to ICU/ICP before PHM
excludeservicelist<-abxculturedata %>%
  select(CSN) %>%
  filter(abxculturedata$BeddedService %like% paste(prePHMservicetoexclude,collapse = "|"))

#apply exclude list
abxculturedata <- abxculturedata %>%
  mutate(reasonforexclusions= if_else(
    CSN %in% excludeservicelist$CSN & reasonforexclusions=="Included","Excluded service",
    if_else(reasonforexclusions!="included",reasonforexclusions,"Included")))

#filter diagnoses that have any of the excluded diagnoses
excludelist<-abxculturedata %>%
  select(CSN) %>%
  filter(str_detect(abxculturedata$ICDdesc, paste(exclusiondiagnoses,collapse='|')))

abxculturedata <- abxculturedata %>%
  mutate(reasonforexclusions= if_else(
    CSN %in% excludelist$CSN & reasonforexclusions=="Included","Excluded diagnosis",
    if_else(reasonforexclusions!="Included",reasonforexclusions,"Included")))

#filter diagnoses that have any other common infections
excludeinfectionlist<-abxculturedata %>%
  select(CSN) %>%
  filter(abxculturedata$ICD %like% paste(exclusioninfections,collapse = "|"))

#apply exclude list
abxculturedata <- abxculturedata %>%
  mutate(reasonforexclusions= if_else(
    CSN %in% excludeinfectionlist$CSN & reasonforexclusions=="Included","Excluded other common infection",
    if_else(reasonforexclusions!="included",reasonforexclusions,"Included")))

#common infections exclusions list 2
excludeinfectionlist2<-abxculturedata %>%
  select(CSN) %>%
  filter(str_detect(abxculturedata$ICDdesc, paste(exclusioninfections2,collapse='|')))

abxculturedata <- abxculturedata %>%
  mutate(reasonforexclusions= if_else(
    CSN %in% excludeinfectionlist2$CSN & reasonforexclusions=="Included","Excluded other common infection",
  if_else(reasonforexclusions!="Included",reasonforexclusions,"Included")))


#exclude selected antimicrobials from med list
abxculturedatanoexcludedmeds<-abxculturedata %>%
  filter(!abxculturedata$Med %like% paste(exclusionantimicrobials,collapse="|"))

excludemedlist<-abxculturedata %>%
  select(CSN) %>%
  filter(!abxculturedata$CSN %in% abxculturedatanoexcludedmeds$CSN)

#label "did not receive abx" only for patients who ONLY received one of the excluded medications and no other antimicrobial
abxculturedata <- abxculturedata %>%
  mutate(reasonforexclusions= if_else(
    CSN %in% excludemedlist$CSN & reasonforexclusions=="Included","Did not receive antibiotic",
  if_else(reasonforexclusions!="Included",reasonforexclusions,"Included")))

#filter out meds that are in the excluded list for patients who recieved other antimicrobials
abxculturedata<-abxculturedata%>%
  filter(!(!CSN %in% excludemedlist & Med %like% paste(exclusionantimicrobials,collapse="|")))

#pna subset
pnasub<-abxculturedata %>%
  select(CSN) %>%
  filter(abxculturedata$ICD %in% pnalist)

abxculturedata <- abxculturedata %>% 
  mutate(reasonforexclusions= if_else(CSN %in% pnasub$CSN & reasonforexclusions=="Included","Included",
                                      if_else(reasonforexclusions!="Included",reasonforexclusions,"No common pnuemonia ICD code"))) 


exclusionsummarytable<-setNames(aggregate(CSN ~ reasonforexclusions, abxculturedata, function(x) length(unique(x))),c("Reason For Exclusion","Count Excluded Encounters"))
exclusionsummarytable<-exclusionsummarytable %>%
  arrange(desc(`Count Excluded Encounters`))

grandtotal<-c("Grand Total",length(unique(abxculturedata$CSN)))
exclusionsummarytable<-rbind(exclusionsummarytable,grandtotal)


exclusionsummarytable



#########FOR TRAIN VALIDATION ONLY########
#exclusions<-abxculturedata %>%
#  filter(reasonforexclusions!="Included")
#write.csv(exclusions,"/Volumes/dmcommon/_DM.Private/CI Program Faculty/+Fellow Franchise/Yarahuan/Protected/Exclusions.csv", row.names = #FALSE)

```


```{r, echo=FALSE,message=FALSE, results=FALSE}
################################# Apply guidelines to assess antibiotic choice ########################################
#find first abx ordered at encounter
abxchoice <- abxculturedata %>%
  group_by(CSN) %>%
  filter(
    MedDT== min(MedDT, na.rm = T) & reasonforexclusions=="Included") 

#create a blank column to store reasons abx are classified as incorrrect: 
abxchoice <- abxchoice %>%
  add_column(label = NA)%>%
  add_column(labeldetailed=NA)

#correct based on defined guidelines in definitions section
abxchoice<-abxchoice %>%
  ungroup()%>%
  mutate(correctinitialabx=case_when(
    Med %in% firstline ~1,
    (Allergy %in% PCNallergy & Med %in% ifPCNallergy)~1,#if allergy to pencillin, then Ceftriaxone, clinda, cefdinir or levofloxacin are correct
    (Allergy %in% cephalosporinallergy & Med %in% ifcephalosporinallergy)~1,#if cephalosporin allergy then clinda or levofloxacin
    (age>ageforazithro & Med==atypicalfirstline)~1,#if over 4 then azithromycin correct,
    (age>ageforazithro & Allergy==azithroallergy & Med %in% atypicalwithazithroallergy)~1, #if over 4 and has azithro allergy
    TRUE~0
  ))

#add reasons for being correct
abxchoice<-abxchoice %>%
  ungroup()%>%
    mutate(label=case_when(
    correctinitialabx==1 ~"Correct",TRUE
    ~"Likely incorrect abx"
  ))%>%
  mutate(labeldetailed=case_when(
    Med %in% firstline ~"First line choice",
    (Allergy %in% PCNallergy & Med %in% ifPCNallergy)~"Correct substitute i/s/o PCN allergy",
    (Allergy %in% cephalosporinallergy & Med %in% ifcephalosporinallergy)~"Correct substitute i/s/o cephalosporin allergy",
    (age>ageforazithro & Med==atypicalfirstline)~"Appropriate age for Azithro use",
    (age>ageforazithro & Allergy==azithroallergy & Med %in% atypicalwithazithroallergy)~"Appropriate age for azithro with appropriate azithro subs i/s/o   Azithro allergy",
    TRUE~"Likely incorrect abx"
  ))

#take max of choice per patietn (this eliminates rows that look false [e.g. patient with multiple drug allergies, recorded as 'incorrect' for one allergy but correct for another])
maxabxchoice<-abxchoice %>% group_by(CSN) %>% top_n(1,correctinitialabx)
  
#summary of correct vs incorrect choices
summarytable1<-maxabxchoice %>%
  group_by(label)%>%
  summarise(count=n_distinct(CSN))%>%
  ungroup()

summarytable1



#Summary of labels (please note that the "correct" count may be higher on this because many patients are ordered for both azithromycin and a first line antibiotic at the same time so the same patient will be in two separate label categories. This does not change the correct/incorrect count)

summarytable2<-maxabxchoice%>%
  group_by(label,labeldetailed)%>%
  summarise(count=n_distinct(CSN))%>%
  ungroup()%>%
  arrange(label,desc(count))
summarytable2

```



## Summary of Correct/Incorrect Orders with Labels [Pre-NLP Analysis]
```{r,echo=FALSE}
###################### Culture Results Analysis ##################

#find history of positive culture preceeding current admission
maxabxchoice <- maxabxchoice %>%
  mutate(hxposculture=NA)

maxabxchoice<-maxabxchoice %>%
  mutate(hxposculture= if_else(((CollectionDT<AdmitDT) & interval(AdmitDT, CollectionDT) %/% months(1) >-12),1,0)) #1 if culture collected before admission within the past 12 months

maxabxchoice<-maxabxchoice %>%
  mutate(correctinitialabx=case_when(
    (correctinitialabx==0 & hxposculture==1 & Susceptibility=='Resistant'& SusceptibilityAntibiotic %in% broadpcnsuscetiblitylist   & (Med=='ceftriaxone'|Med=='clindamycin'|Med=='cefdinir'|Med=='cephalexin')) ~1,
     (correctinitialabx==0 &hxposculture==1 & Susceptibility=='Resistant'& SusceptibilityAntibiotic %in% narrowpcnsusceptibilitylist   & (Med=='ceftriaxone'|Med=='cephalexin'|Med=='cefdinir'|Med=='amoxicillin-clavulanate'|Med=='ampicillin-sulbactam')) ~1,
    TRUE~correctinitialabx
  ))

maxabxchoice<-maxabxchoice %>%
  mutate(labeldetailed=case_when(
    (correctinitialabx==0 & hxposculture==1 & Susceptibility=='Resistant'& SusceptibilityAntibiotic %in% broadpcnsuscetiblitylist   & (Med=='ceftriaxone'|Med=='clindamycin'|Med=='cefdinir'|Med=='cephalexin')) ~"Prior Resistant Culture",
     (correctinitialabx==0 &hxposculture==1 & Susceptibility=='Resistant'& SusceptibilityAntibiotic %in% narrowpcnsusceptibilitylist   & (Med=='ceftriaxone'|Med=='cephalexin'|Med=='cefdinir'|Med=='amoxicillin-clavulanate'|Med=='ampicillin-sulbactam')) ~"Prior Resistant Culture",
    TRUE~labeldetailed
  ))

#take max of choice per patietn
maxabxchoice<-abxchoice %>% group_by(CSN) %>% top_n(1,correctinitialabx)

#summary of correct vs incorrect choices
summarytable2<-maxabxchoice %>%
  group_by(label)%>%
  summarise(count=n_distinct(CSN))%>%
  ungroup()
summarytable2

```



```{r, echo=FALSE}
################################# get list of all remaining patients who are incorrect for NLP below ########################################

#get CSN list of remaining "incorrect" patients
csnlist<-maxabxchoice[maxabxchoice$correctinitialabx == 0, ]
csnlist<-unique(csnlist$CSN)

#save CSN list as CSV

#write.csv(csnlist,"/Volumes/dmcommon/_DM.Private/CI Program Faculty/+Fellow Franchise/Yarahuan/Protected/CSNList.csv", row.names = FALSE)
```



```{r,echo=FALSE, message=FALSE}
################################# Start NLP ########################################################

#File path variable: Input your file path to note contents file here
notefile="/Volumes/dmcommon/_DM.Private/CI Program Faculty/+Fellow Franchise/Yarahuan/Protected/NoteContents.csv"


#Load Datasets
notedata <- read_csv(notefile)

#NoteData Columns
#1=CSN, 2=NoteDT, 3=NoteType, 4=NoteText

#rename columns
notedata<-notedata %>%
  rename(CSN=1) %>%
  rename(NoteDT=2) %>%
  rename(NoteType=3) %>%
  rename(NoteText=4)

#make text columns lowercase
notedata$NoteType=tolower(notedata$NoteType)

```

```{r}
#testing regex with word boundaries
testingphrases<-"(?i)(RLL|RUL)\\s+(pneumonia)"

testphrases<-notedata %>%
  filter(str_detect(notedata$NoteText, testingphrases))
```

```{r, echo=FALSE,message=FALSE}
################################# Create your NLP phrases ########################################################
#treatment failure phrases
treatmentfailurephrases<-"(?i)(?!unlikely|less likely|did not|no|has no|didn't|hasn't|has not yet|hasn't yet|did not yet|didn't yet)\\s+(treatment failure|failed outpatient\\s+(?:treatment|therapy|antibiotics|antibiotic|amoxicillin|HD amoxicillin|high-dose amoxicillin|high dose amoxicillin|HD amoxicillin)|failure of outpatient\\s+(?:treatment|therapy|antibiotics|antibiotic|amoxicillin|HD amoxicillin|high-dose amoxicillin|high dose amoxicillin)|despite\\s+(?:treatment|therapy|antibiotics|antibiotic|amoxicillin|HD amoxicillin|high-dose amoxicillin|high dose amoxicillin |outpatient\\s+(?:treatment|therapy|antibiotics|antibiotic|amoxicillin|HD amoxicillin|high-dose amoxicillin|high dose amoxicillin))|(?:in spite of |s p|sp|s/p)\\s+outpatient\\s+(?:treatment|therapy|antibiotics|antibiotic|amoxicillin|HD amoxicillin|high-dose amoxicillin|high dose amoxicillin)|started on\\s+(?:treatment|therapy|antibiotics|antibiotic|amoxicillin|HD amoxicillin|high-dose amoxicillin|high dose amoxicillin)\\s+as\\s+(?:outpatient|an outpatient))"

#NLP notes: 
###"(?i)" at the beginning of the pattern indicates that the search should be case-insensitive
###"(?!unlikely|less likely|did not|has no|didn't|hasn't|has not yet|hasn't yet|did not yet|didn't yet)" part of the pattern is a negative lookahead assertion that will cause the regular expression to fail if any of the specified substrings are present. This will prevent the regular expression from matching phrases that contain the words "unlikely", "less likely", "did not", "has no", "didn't", "hasn't", "has not yet", "hasn't yet", "did not yet", or "didn't yet".
### (?:) non-capturing group to group together common parts of the phrases. 
#****add more description about above
#***add more description mandatory vs optional
#*work through straightforward example
#\\includes a whitespace character

#aspiration phrases
aspirationphrases="(?i)(?<!unlikely|less likely|is unlikely|is less likely|no|not|notlikely|reassuring against|no concern for|am not concerned for|no history of|no recent episodes of|history of|no clear)\\s+(aspiration pneumonia|likely aspiration|aspiration event|presumed aspiration|empirically for aspiration|cover for aspiration|treat for aspiration|aspiration coverage|aspiration treatment)(?!\\s+unlikely|\\s+less likely|\\s+is unlikely|\\s+is less likely|\\s+not likely|\\s+is not likely|\\s+is not needed|\\s+is not necessary)"

#immunization phrases
unimmunizedphrases="(?i)unimmunized|unvaccinated|partially\\s+(vaccinated|immunized)|not\\s+(immunized|fully immunized|up to date on immunizations|vaccinated|fully vaccinated)|immunizations\\s+(not up to date|are not up to date|incomplete)|incomplete\\s+(immunizations|vaccinations)"

#critical illness phrases
criticalillnessphrases="(?i)(?<!no|not|not in|no signs of|no sign of|not concerned for|no concern for|reassured against|reassuring against|no evidence of|not suggestive of)\\s+(?:shock|critically ill|sepsis|critical illness|septic)"

#pleural effusion
pleuraleffusionphrases="(?i)(?<!no|no signs of a?|no sign of a?|not concerned for a?|no concern for a?|reassured against a?|reassuring against a?|no evidence of a?|not suggestive of a?)\\s+((moderate|large|complex|loculated)\\s+(pleural|parapneumonic)\\s+effusion)"

#immunocomrpomised
immunesuppressionphrases="(?i)(?<!no|not|no signs of|no sign of|not concerned for|no concern for|reassured against|reassuring against|no evidence of|not suggestive of)\\s+(immunosuppressed|immunocompromised|immune compromised|immune suppressed|immunodeficiency|immunodeficient|immune deficiency|immune deficient)"

```


## Summary of NLP findings
```{r,echo=FALSE,message=FALSE}
################################# Apply NLP phrases ########################################################

#apply treatment failure phrases
treatmentfailure<-notedata %>%
  select(CSN) %>%
  filter(str_detect(notedata$NoteText, treatmentfailurephrases))

#apply aspiration phrases
aspiration<-notedata %>%
  select(CSN) %>%
  filter(str_detect(notedata$NoteText, aspirationphrases))

#apply unimmunized phrases
unimmunized<-notedata %>%
  select(CSN) %>%
  filter(str_detect(notedata$NoteText, unimmunizedphrases))

#apply critical illness phrases
criticalillness<-notedata %>%
  select(CSN) %>%
  filter(str_detect(notedata$NoteText, criticalillnessphrases))

#apply pleural effusion phrases
pleuraleffusion<-notedata %>%
  select(CSN) %>%
  filter(str_detect(notedata$NoteText, pleuraleffusionphrases))

#apply immune suppressed phrases
immunesuppressed<-notedata %>%
  select(CSN) %>%
  filter(str_detect(notedata$NoteText, immunesuppressionphrases))


#get all CSNs from above lists
treatmentfailurecsnlist<-unique(treatmentfailure$CSN)
aspirationcsnlist<-unique(aspiration$CSN)
unimmunizedcsnlist<-unique(unimmunized$CSN)
criticalillnesscsnlist<-unique(criticalillness$CSN)
pleuraleffusioncsnlist<-unique(pleuraleffusion$CSN)
immunosuppressedcsnlist<-unique(immunesuppressed$CSN)


#if CSN in treatmnet failure list
maxabxchoice<-maxabxchoice %>%
  ungroup()%>%
  mutate(correctinitialabx= if_else(maxabxchoice$CSN %in% treatmentfailurecsnlist
                                    ,2,correctinitialabx,correctinitialabx)) %>%
  mutate(label= if_else(maxabxchoice$CSN %in% treatmentfailurecsnlist
                                    ,"Needs Review",label,label)) %>%
  mutate(labeldetailed= if_else(maxabxchoice$CSN %in% treatmentfailurecsnlist
                                    ,"Outpatient treatment failure",labeldetailed,labeldetailed))

#if CSN in aspiration list
maxabxchoice<-maxabxchoice %>%
  ungroup()%>%
  mutate(correctinitialabx= if_else(maxabxchoice$CSN %in% aspirationcsnlist
                                    ,2,correctinitialabx,correctinitialabx)) %>%
  mutate(label= if_else(maxabxchoice$CSN %in% aspirationcsnlist
                                    ,"Needs Review",label,label)) %>%
  mutate(labeldetailed= if_else(maxabxchoice$CSN %in% aspirationcsnlist
                                    ,"Aspiration pneumonia",labeldetailed,labeldetailed))

#if CSN in unimmunized list
maxabxchoice<-maxabxchoice %>%
  ungroup()%>%
  mutate(correctinitialabx= if_else(maxabxchoice$CSN %in% unimmunizedcsnlist
                                    ,2,correctinitialabx,correctinitialabx)) %>%
  mutate(label= if_else(maxabxchoice$CSN %in% unimmunizedcsnlist
                                    ,"Needs Review",label,label))%>%
  mutate(labeldetailed= if_else(maxabxchoice$CSN %in% unimmunizedcsnlist
                                    ,"Unimmunized",labeldetailed,labeldetailed))

#if CSN in critical illness list
maxabxchoice<-maxabxchoice %>%
  ungroup()%>%
  mutate(correctinitialabx= if_else(maxabxchoice$CSN %in% criticalillnesscsnlist
                                    ,2,correctinitialabx,correctinitialabx)) %>%
  mutate(label= if_else(maxabxchoice$CSN %in% criticalillnesscsnlist
                                    ,"Needs Review",label,label))%>%
  mutate(labeldetailed= if_else(maxabxchoice$CSN %in% criticalillnesscsnlist
                                    ,"Critically ill",labeldetailed,labeldetailed))

#if CSN in pleural effusion list
maxabxchoice<-maxabxchoice %>%
  ungroup()%>%
  mutate(correctinitialabx= if_else(maxabxchoice$CSN %in% pleuraleffusioncsnlist
                                    ,2,correctinitialabx,correctinitialabx)) %>%
  mutate(label= if_else(maxabxchoice$CSN %in% pleuraleffusioncsnlist
                                    ,"Needs Review",label,label))%>%
  mutate(labeldetailed= if_else(maxabxchoice$CSN %in% pleuraleffusioncsnlist
                                    ,"Large/Complicated Pleural Effusion",labeldetailed,labeldetailed))

#if CSN in immunoesuppressed list
maxabxchoice<-maxabxchoice %>%
  ungroup()%>%
  mutate(correctinitialabx= if_else(maxabxchoice$CSN %in% immunosuppressedcsnlist
                                    ,2,correctinitialabx,correctinitialabx)) %>%
  mutate(label= if_else(maxabxchoice$CSN %in% immunosuppressedcsnlist
                                    ,"Needs Review",label,label))%>%
  mutate(labeldetailed= if_else(maxabxchoice$CSN %in% immunosuppressedcsnlist
                                    ,"Large/Complicated Pleural Effusion",labeldetailed,labeldetailed))


#define guidelinechoices (if unimmunized then--> Ceftriaxone, cefotaxime, cefdinir, levofloxacin)
optreatmentorunimmunized=c("ceftriaxone","cefotaxime","cefdinir","levofloxacin")

#apply guidelines for unimmunized patient
maxabxchoice<-maxabxchoice %>%
  mutate(correctinitialabx= if_else((labeldetailed=="Unimmunized")&(Med %in% optreatmentorunimmunized),1,correctinitialabx,correctinitialabx))%>%
  mutate(label= if_else((labeldetailed=="Unimmunized")&(Med %in% optreatmentorunimmunized),"Correct",label,label))%>%
  mutate(labeldetailed= if_else((labeldetailed=="Unimmunized")&(Med %in% optreatmentorunimmunized),"Correct substitute for unimmunzed",labeldetailed,labeldetailed))

#max per patient   
maxabxchoice<-maxabxchoice %>% group_by(CSN) %>% 
  mutate(correctinitialabx= max(correctinitialabx)) %>%
  ungroup()

#take max of choice per patietn
maxabxchoice<-maxabxchoice %>% group_by(CSN) %>% 
  mutate(correctinitialabx= max(correctinitialabx)) %>%
  ungroup()

maxabxchoice %>%
  group_by(label)%>%
  summarise(count=n_distinct(CSN))%>%
  ungroup()%>%
  arrange(desc(count))

maxabxchoice %>%
  group_by(label,labeldetailed)%>%
  summarise(count=n_distinct(CSN))%>%
  ungroup()%>%
  arrange(label,desc(count))

```

```{r}
############ get phrase's ID and note context around phrases ########

######combine all phrases and CSN's#######3
allNLP_phrases<-c(paste(treatmentfailurephrases,collapse = "|"),paste(aspirationphrases,collapse = "|"),paste(unimmunizedphrases,collapse = "|"),paste(criticalillnessphrases,collapse = "|"),paste(pleuraleffusionphrases,collapse = "|"),paste(immunesuppressionphrases,collapse = "|"))
all_CSN_NLP_list<-c(treatmentfailurecsnlist,aspirationcsnlist,unimmunizedcsnlist,criticalillnesscsnlist,pleuraleffusioncsnlist,immunosuppressedcsnlist)
#make new columns
notedata<-notedata%>%
  mutate(startposition="NA") %>%
  mutate(endposition="NA")%>%
  mutate(context="NA")

#show phrase captured in column
notedata<-notedata %>%
  ungroup()%>%
  mutate(identifiedphrase= if_else(notedata$CSN %in% all_CSN_NLP_list
                                  ,str_extract(notedata$NoteText,paste(allNLP_phrases,collapse = "|")),""))

####for loop 
for(i in 1:nrow(notedata)) {       # for-loop over rows
 notedata$startposition[i]<-((str_locate(notedata$NoteText[i],notedata$identifiedphrase[i])[,1])-120)
 notedata$endposition[i]<-((str_locate(notedata$NoteText[i],notedata$identifiedphrase[i])[,2])+120)
 notedata$context[i]=str_sub(notedata$NoteText[i],start=(notedata$startposition[i]),end=(notedata$endposition[i]))
}

#######Show summary statistics for phrases
notedatasummary<-notedata %>%
  group_by(identifiedphrase)%>%
  summarise(count=n_distinct(CSN))%>%
  ungroup()%>%
  arrange(desc(count))

notedatasummary

####Creat table for easy phrase/context manual review
notedatacontext<-notedata%>%
  select(CSN,NoteDT,NoteType,identifiedphrase,context,)

notedatacontext
#save CSN list as CSV

#write.csv(notedatacontext,"/Volumes/dmcommon/_DM.Private/CI Program Faculty/+Fellow Franchise/Yarahuan/Protected/NoteDataContext.csv", row.names = FALSE)

```

```{r}
#testing

#make table of all NLP + full note text to quickly review!
notedata
#write.csv(notedata,"/Volumes/dmcommon/_DM.Private/CI Program Faculty/+Fellow Franchise/Yarahuan/Protected/NoteDataForTesting.csv", row.names = FALSE)

#make table of all without phrase ID + full note text to quickly review!

```


```{r}
#########TRAIN/TEST ONLY########

#format output for manual review

#review exclusions
abxculturedata
#write.csv(abxculturedata,"/Volumes/dmcommon/_DM.Private/CI Program Faculty/+Fellow Franchise/Yarahuan/Protected/Exclusions.csv", row.names = FALSE)

#join main table with NLP note context
trainreview= maxabxchoice %>% left_join(notedatacontext,by="CSN")
write.csv(trainreview,"/Volumes/dmcommon/_DM.Private/CI Program Faculty/+Fellow Franchise/Yarahuan/Protected/TrainReview.csv", row.names = FALSE)
```

